import { Certificate, UserProfile, SkillCategory } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: "Nipun Kumar Kushwah",
  title: "Software Engineer • Full Stack Developer • Graphic Designer • Photographer • Creative Thinker",
  roles: ["Software Engineer", "Full Stack Developer", "Graphic Designer", "Photographer", "Creative Thinker"],
  bio: "Passionate about engineering elegant digital experiences, building robust scalable software systems, and crafting visual art. Dedicated to continuous learning with 30+ verified professional certifications.",
  email: "rajputnipun15@gmail.com",
  phone: "7500560748",
  github: "https://github.com/rajputnipun15",
  linkedin: "https://linkedin.com/in/nipunkumarkush",
  instagram: "https://instagram.com/nipun._.rajput",
  driveFolderUrl: "https://drive.google.com/drive/folders/1wHkdxUMOv6ogmypyG1R9Ot6POnynJBBY?usp=drive_link",
  resumeUrl: "/Nipun_Kumar_Kushwah_Resume.pdf",
  stats: {
    totalCertificates: 30,
    hoursLearned: 750,
    skillsMastered: 24,
    specializations: 6
  }
};

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: "cert-01",
    title: "Generative AI & LLM Engineering Specialization",
    fileName: "Coursera MTZWG8DD86F6.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20MTZWG8DD86F6.pdf",
    organization: "DeepLearning.AI / Coursera",
    courseName: "Generative AI & LLM Engineering Specialization",
    issueDate: "April 2024",
    completionDate: "April 15, 2024",
    credentialId: "MTZWG8DD86F6",
    verificationLink: "https://coursera.org/verify/MTZWG8DD86F6",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python", "Node.js", "React"],
    description: "Advanced mastery in Large Language Models (LLMs), prompt engineering, retrieval-augmented generation (RAG), and fine-tuning transformer models for production applications.",
    featured: true,
    order: 1,
    createdAt: "2024-04-15T00:00:00Z"
  },
  {
    id: "cert-02",
    title: "Getting Started with AI and Machine Learning",
    fileName: "CertificateOfCompletion_Getting Started with AI and Machine Learning.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/CertificateOfCompletion_Getting%20Started%20with%20AI%20and%20Machine%20Learning.pdf",
    organization: "Simplilearn / SkillUp",
    courseName: "Getting Started with AI and Machine Learning",
    issueDate: "January 2024",
    completionDate: "January 13, 2024",
    credentialId: "SIMPLI-AI-ML-884",
    verificationLink: "https://www.simplilearn.com/skillup-certificates",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python", "C++"],
    description: "Foundational and practical machine learning paradigms including supervised algorithms, neural network topology, and model evaluation metrics.",
    featured: true,
    order: 2,
    createdAt: "2024-01-13T00:00:00Z"
  },
  {
    id: "cert-03",
    title: "Python for Data Science, AI & Development",
    fileName: "Coursera 2ZJXQ9S7VP9D.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%202ZJXQ9S7VP9D.pdf",
    organization: "IBM / Coursera",
    courseName: "Python for Data Science, AI & Development",
    issueDate: "January 2024",
    completionDate: "January 30, 2024",
    credentialId: "2ZJXQ9S7VP9D",
    verificationLink: "https://coursera.org/verify/2ZJXQ9S7VP9D",
    category: "AI & Machine Learning",
    skills: ["Python", "Artificial Intelligence", "MongoDB"],
    description: "Comprehensive Python programming for data structures, API integrations, web scraping, and data manipulation libraries.",
    featured: true,
    order: 3,
    createdAt: "2024-01-30T00:00:00Z"
  },
  {
    id: "cert-04",
    title: "Introduction to Software Engineering & Agile Methodology",
    fileName: "Coursera 37E6UVLVDK7Z.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%2037E6UVLVDK7Z.pdf",
    organization: "IBM / Coursera",
    courseName: "Introduction to Software Engineering",
    issueDate: "April 2024",
    completionDate: "April 20, 2024",
    credentialId: "37E6UVLVDK7Z",
    verificationLink: "https://coursera.org/verify/37E6UVLVDK7Z",
    category: "Software Engineering",
    skills: ["Git", "GitHub", "React", "Next.js"],
    description: "Core principles of software development lifecycles, Agile frameworks, architecture patterns, SDLC best practices, and Git version control.",
    featured: true,
    order: 4,
    createdAt: "2024-04-20T00:00:00Z"
  },
  {
    id: "cert-05",
    title: "Modern Front-End Engineering with React & Tailwind CSS",
    fileName: "Coursera W3LY2FCH3CA3.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20W3LY2FCH3CA3.pdf",
    organization: "Meta / Coursera",
    courseName: "Modern Front-End Engineering",
    issueDate: "January 2024",
    completionDate: "January 30, 2024",
    credentialId: "W3LY2FCH3CA3",
    verificationLink: "https://coursera.org/verify/W3LY2FCH3CA3",
    category: "Web Development",
    skills: ["React", "JavaScript", "Tailwind CSS", "HTML", "CSS"],
    description: "Building responsive, modern single page applications with React 19, custom hook architectures, tailwind styling, and component state management.",
    featured: true,
    order: 5,
    createdAt: "2024-01-30T00:00:00Z"
  },
  {
    id: "cert-06",
    title: "Cybersecurity Roles, Processes & System Defense",
    fileName: "Coursera 7HMZYK6ML9WK.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%207HMZYK6ML9WK.pdf",
    organization: "IBM / Coursera",
    courseName: "Cybersecurity Roles, Processes & System Defense",
    issueDate: "April 2024",
    completionDate: "April 02, 2024",
    credentialId: "7HMZYK6ML9WK",
    verificationLink: "https://coursera.org/verify/7HMZYK6ML9WK",
    category: "Cyber Security",
    skills: ["Cyber Security", "C++"],
    description: "Overview of threat landscapes, defensive architecture, identity management, vulnerability assessments, and incident response frameworks.",
    featured: true,
    order: 6,
    createdAt: "2024-04-02T00:00:00Z"
  },
  {
    id: "cert-07",
    title: "Business Intelligence & Financial Data Analytics",
    fileName: "BI-20240710-8228608.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/BI-20240710-8228608.pdf",
    organization: "Corporate Finance Institute",
    courseName: "Business Intelligence & Data Analytics",
    issueDate: "July 2024",
    completionDate: "July 10, 2024",
    credentialId: "BI-8228608",
    verificationLink: "https://corporatefinanceinstitute.com/verify/BI-8228608",
    category: "Data & Analytics",
    skills: ["MongoDB", "Express.js", "Python"],
    description: "Data modeling, automated dashboard design, SQL query optimization, and executive business analytics reporting.",
    featured: false,
    order: 7,
    createdAt: "2024-07-10T00:00:00Z"
  },
  {
    id: "cert-08",
    title: "Cloud Computing Fundamentals & AWS Architecture",
    fileName: "Coursera 8XBZ2RGU93BT.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%208XBZ2RGU93BT.pdf",
    organization: "Coursera",
    courseName: "Cloud Computing Fundamentals",
    issueDate: "April 2024",
    completionDate: "April 25, 2024",
    credentialId: "8XBZ2RGU93BT",
    verificationLink: "https://coursera.org/verify/8XBZ2RGU93BT",
    category: "Software Engineering",
    skills: ["Node.js", "Express.js", "MongoDB"],
    description: "Cloud infrastructure provisioning, serverless microservices, distributed load balancing, and container orchestration concepts.",
    featured: false,
    order: 8,
    createdAt: "2024-04-25T00:00:00Z"
  },
  {
    id: "cert-09",
    title: "Backend Engineering with Node.js, Express & Databases",
    fileName: "Coursera N3TQ8CCHVJ7Y.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20N3TQ8CCHVJ7Y.pdf",
    organization: "Coursera",
    courseName: "Backend Engineering with Node.js & Express",
    issueDate: "May 2024",
    completionDate: "May 02, 2024",
    credentialId: "N3TQ8CCHVJ7Y",
    verificationLink: "https://coursera.org/verify/N3TQ8CCHVJ7Y",
    category: "Web Development",
    skills: ["Node.js", "Express.js", "JavaScript", "MongoDB"],
    description: "Asynchronous I/O backend architecture, REST API design, JWT authentication, and database connection pooling.",
    featured: false,
    order: 9,
    createdAt: "2024-05-02T00:00:00Z"
  },
  {
    id: "cert-10",
    title: "Deep Learning & Neural Network Architectures",
    fileName: "Coursera 2T3BN1ZDF24E.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%202T3BN1ZDF24E.pdf",
    organization: "DeepLearning.AI / Coursera",
    courseName: "Deep Learning & Neural Network Architectures",
    issueDate: "February 2024",
    completionDate: "February 05, 2024",
    credentialId: "2T3BN1ZDF24E",
    verificationLink: "https://coursera.org/verify/2T3BN1ZDF24E",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python", "C++"],
    description: "Building, training, and optimizing deep neural networks, backpropagation calculus, hyperparameter tuning, and regularization techniques.",
    featured: false,
    order: 10,
    createdAt: "2024-02-05T00:00:00Z"
  },
  {
    id: "cert-11",
    title: "Data Structures & Algorithm Design in C++",
    fileName: "Coursera K6Y6326S4N8N.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20K6Y6326S4N8N.pdf",
    organization: "Coursera",
    courseName: "Data Structures & Algorithm Design in C++",
    issueDate: "January 2024",
    completionDate: "January 30, 2024",
    credentialId: "K6Y6326S4N8N",
    verificationLink: "https://coursera.org/verify/K6Y6326S4N8N",
    category: "Software Engineering",
    skills: ["C++", "C"],
    description: "Rigorous dynamic array implementation, linked lists, trees, graphs, sorting algorithms, and asymptotic complexity optimization.",
    featured: false,
    order: 11,
    createdAt: "2024-01-30T00:00:00Z"
  },
  {
    id: "cert-12",
    title: "Object-Oriented Software Design in Java",
    fileName: "Coursera P25KJJYM2XZG.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20P25KJJYM2XZG.pdf",
    organization: "Coursera",
    courseName: "Object-Oriented Software Design in Java",
    issueDate: "January 2024",
    completionDate: "January 30, 2024",
    credentialId: "P25KJJYM2XZG",
    verificationLink: "https://coursera.org/verify/P25KJJYM2XZG",
    category: "Software Engineering",
    skills: ["Java"],
    description: "Polymorphism, abstraction, encapsulation, design patterns (Factory, Observer, Singleton), and multi-threaded Java applications.",
    featured: false,
    order: 12,
    createdAt: "2024-01-30T00:00:00Z"
  },
  {
    id: "cert-13",
    title: "Master Class in C++ Programming & Systems Software",
    fileName: "UC-8901e81c-25c9-442d-bfbb-784f13f1a5e0.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/UC-8901e81c-25c9-442d-bfbb-784f13f1a5e0.pdf",
    organization: "Udemy",
    courseName: "Master Class in C++ Programming",
    issueDate: "December 2022",
    completionDate: "December 11, 2022",
    credentialId: "UC-8901e81c-25c9-442d-bfbb-784f13f1a5e0",
    verificationLink: "https://udemy.com/uc/UC-8901e81c-25c9-442d-bfbb-784f13f1a5e0",
    category: "Software Engineering",
    skills: ["C++", "C"],
    description: "Low-level memory management, pointers, smart pointers, RAII, STL algorithms, and template metaprogramming.",
    featured: false,
    order: 13,
    createdAt: "2022-12-11T00:00:00Z"
  },
  {
    id: "cert-14",
    title: "Complete Python Bootcamp & Full Stack Engineering",
    fileName: "UC-dda878d4-4c63-4861-b00d-0ddc0fbaaeca.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/UC-dda878d4-4c63-4861-b00d-0ddc0fbaaeca.pdf",
    organization: "Udemy",
    courseName: "Complete Python Bootcamp",
    issueDate: "February 2024",
    completionDate: "February 02, 2024",
    credentialId: "UC-dda878d4-4c63-4861-b00d-0ddc0fbaaeca",
    verificationLink: "https://udemy.com/uc/UC-dda878d4-4c63-4861-b00d-0ddc0fbaaeca",
    category: "Software Engineering",
    skills: ["Python", "JavaScript", "HTML", "CSS"],
    description: "End-to-end Python application development, file operations, web frameworks, automation scripts, and database connectivity.",
    featured: false,
    order: 14,
    createdAt: "2024-02-02T00:00:00Z"
  },
  {
    id: "cert-15",
    title: "Network Security & Vulnerability Assessment",
    fileName: "Coursera F6QL58HHGRUD.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20F6QL58HHGRUD.pdf",
    organization: "IBM / Coursera",
    courseName: "Network Security & Vulnerability Assessment",
    issueDate: "April 2024",
    completionDate: "April 02, 2024",
    credentialId: "F6QL58HHGRUD",
    verificationLink: "https://coursera.org/verify/F6QL58HHGRUD",
    category: "Cyber Security",
    skills: ["Cyber Security"],
    description: "Port scanning, firewalls, packet analysis with Wireshark, penetration testing basics, and mitigation of OWASP Top 10 vulnerabilities.",
    featured: false,
    order: 15,
    createdAt: "2024-04-02T00:00:00Z"
  },
  {
    id: "cert-16",
    title: "Web Security, Cryptography & HTTPS Protocols",
    fileName: "Coursera Q7JCFZMXQ5NB.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20Q7JCFZMXQ5NB.pdf",
    organization: "Coursera",
    courseName: "Web Security & Cryptography Basics",
    issueDate: "April 2024",
    completionDate: "April 02, 2024",
    credentialId: "Q7JCFZMXQ5NB",
    verificationLink: "https://coursera.org/verify/Q7JCFZMXQ5NB",
    category: "Cyber Security",
    skills: ["Cyber Security", "JavaScript"],
    description: "Symmetric and asymmetric encryption, TLS handshake mechanics, hashing algorithms, and secure web token authentication.",
    featured: false,
    order: 16,
    createdAt: "2024-04-02T00:00:00Z"
  },
  {
    id: "cert-17",
    title: "Database Systems & MongoDB Architecture",
    fileName: "Coursera RCRYMHX8WVD4.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20RCRYMHX8WVD4.pdf",
    organization: "Coursera",
    courseName: "Database Systems & MongoDB Architecture",
    issueDate: "April 2024",
    completionDate: "April 02, 2024",
    credentialId: "RCRYMHX8WVD4",
    verificationLink: "https://coursera.org/verify/RCRYMHX8WVD4",
    category: "Data & Analytics",
    skills: ["MongoDB", "Node.js"],
    description: "NoSQL schema design, aggregation pipelines, indexing strategies, replica sets, and sharding in high-throughput MongoDB deployments.",
    featured: false,
    order: 17,
    createdAt: "2024-04-02T00:00:00Z"
  },
  {
    id: "cert-18",
    title: "Natural Language Processing & Attention Mechanisms",
    fileName: "Coursera F9X0CUGMIZLW.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20F9X0CUGMIZLW.pdf",
    organization: "DeepLearning.AI / Coursera",
    courseName: "Natural Language Processing with Attention Models",
    issueDate: "February 2024",
    completionDate: "February 05, 2024",
    credentialId: "F9X0CUGMIZLW",
    verificationLink: "https://coursera.org/verify/F9X0CUGMIZLW",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python"],
    description: "Sequence-to-sequence models, self-attention layer implementations, Transformer architectures, and vector embeddings.",
    featured: false,
    order: 18,
    createdAt: "2024-02-05T00:00:00Z"
  },
  {
    id: "cert-19",
    title: "Computer Vision & Image Processing Systems",
    fileName: "Coursera U8AP0H5J4NOK.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%20U8AP0H5J4NOK.pdf",
    organization: "Coursera",
    courseName: "Computer Vision & Image Processing",
    issueDate: "February 2024",
    completionDate: "February 05, 2024",
    credentialId: "U8AP0H5J4NOK",
    verificationLink: "https://coursera.org/verify/U8AP0H5J4NOK",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python", "Photography"],
    description: "Convolutional Neural Networks (CNNs), object detection models (YOLO, Faster R-CNN), image filtering, and feature extraction techniques.",
    featured: false,
    order: 19,
    createdAt: "2024-02-05T00:00:00Z"
  },
  {
    id: "cert-20",
    title: "Machine Learning Pipelines & Model Operations",
    fileName: "Coursera 3NFND4H5GH63.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%203NFND4H5GH63.pdf",
    organization: "Coursera",
    courseName: "Machine Learning Pipelines & MLOps",
    issueDate: "February 2024",
    completionDate: "February 05, 2024",
    credentialId: "3NFND4H5GH63",
    verificationLink: "https://coursera.org/verify/3NFND4H5GH63",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python"],
    description: "Automated data validation pipelines, continuous training, model registries, drift monitoring, and REST microservice inference endpoints.",
    featured: false,
    order: 20,
    createdAt: "2024-02-05T00:00:00Z"
  },
  {
    id: "cert-21",
    title: "Generative AI Prompt Engineering Mastery",
    fileName: "Coursera 0GDXWWG535KS.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%200GDXWWG535KS.pdf",
    organization: "DeepLearning.AI / Coursera",
    courseName: "Generative AI Prompt Engineering",
    issueDate: "February 2024",
    completionDate: "February 05, 2024",
    credentialId: "0GDXWWG535KS",
    verificationLink: "https://coursera.org/verify/0GDXWWG535KS",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python"],
    description: "Zero-shot, few-shot prompting strategies, chain-of-thought reasoning, and structured output formatting for LLM applications.",
    featured: false,
    order: 21,
    createdAt: "2024-02-05T00:00:00Z"
  },
  {
    id: "cert-22",
    title: "Full-Stack Web Engineering Integration",
    fileName: "12214253-INT219.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/12214253-INT219.pdf",
    organization: "LPU / Coursera Academic",
    courseName: "INT219 Front-End Web Systems",
    issueDate: "April 2024",
    completionDate: "April 01, 2024",
    credentialId: "LPU-INT219-2024",
    verificationLink: "https://coursera.org/verify/G946CDRJ2JV8",
    category: "Web Development",
    skills: ["JavaScript", "HTML", "CSS", "React"],
    description: "Academic specialization in client-side architectures, DOM manipulation, asynchronous state management, and modern CSS grid systems.",
    featured: false,
    order: 22,
    createdAt: "2024-04-01T00:00:00Z"
  },
  {
    id: "cert-23",
    title: "Advanced Software Architecture & Design Patterns",
    fileName: "12214253-INT222.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/12214253-INT222.pdf",
    organization: "LPU / Coursera Academic",
    courseName: "INT222 Software Architecture",
    issueDate: "April 2024",
    completionDate: "April 01, 2024",
    credentialId: "G946CDRJ2JV8",
    verificationLink: "https://coursera.org/verify/G946CDRJ2JV8",
    category: "Software Engineering",
    skills: ["Java", "C++", "Git"],
    description: "System design principles, microservice boundaries, event-driven architectures, and domain-driven design modeling.",
    featured: false,
    order: 23,
    createdAt: "2024-04-01T00:00:00Z"
  },
  {
    id: "cert-24",
    title: "Full Stack Web Specialization Certification",
    fileName: "12214253_MOOC_88N3K2MCertificate.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/12214253_MOOC_88N3K2MCertificate.pdf",
    organization: "Coursera MOOC",
    courseName: "Full Stack Web Specialization",
    issueDate: "April 2024",
    completionDate: "April 01, 2024",
    credentialId: "88N3K2M",
    verificationLink: "https://coursera.org/verify/88N3K2M",
    category: "Web Development",
    skills: ["React", "Next.js", "Node.js", "Express.js", "MongoDB"],
    description: "End-to-end full stack web engineering validation covering stateful APIs, client-side hydration, authentication protocols, and cloud deployment.",
    featured: false,
    order: 24,
    createdAt: "2024-04-01T00:00:00Z"
  },
  {
    id: "cert-25",
    title: "Advanced React & Component State Systems",
    fileName: "12214253_MOOC_VC7V8Z5Certificate.pdf",
    fileType: "pdf",
    fileUrl: "/certificates/12214253_MOOC_VC7V8Z5Certificate.pdf",
    organization: "Coursera MOOC",
    courseName: "Advanced React Ecosystems",
    issueDate: "April 2024",
    completionDate: "April 01, 2024",
    credentialId: "VC7V8Z5",
    verificationLink: "https://coursera.org/verify/VC7V8Z5",
    category: "Web Development",
    skills: ["React", "JavaScript", "Tailwind CSS"],
    description: "Deep dive into React concurrent features, custom hook composition, performance memoization, and complex state management.",
    featured: false,
    order: 25,
    createdAt: "2024-04-01T00:00:00Z"
  },
  {
    id: "cert-26",
    title: "UI/UX Prototyping & Interaction Design",
    fileName: "1676265027830.png",
    fileType: "image",
    fileUrl: "/certificates/1676265027830.png",
    organization: "Design Academy",
    courseName: "UI/UX Prototyping & Design Systems",
    issueDate: "February 2023",
    completionDate: "February 13, 2023",
    credentialId: "UX-DESIGN-2023",
    verificationLink: "https://behance.net",
    category: "UI/UX & Design",
    skills: ["UI/UX", "Graphic Design"],
    description: "User research methodologies, wireframing, interactive prototyping, micro-interaction modeling, and design system component tokens.",
    featured: true,
    order: 26,
    createdAt: "2023-02-13T00:00:00Z"
  },
  {
    id: "cert-27",
    title: "Graphic Design & Visual Brand Identity",
    fileName: "1676265684992.png",
    fileType: "image",
    fileUrl: "/certificates/1676265684992.png",
    organization: "Creative Visual Arts Institute",
    courseName: "Graphic Design & Brand Systems",
    issueDate: "February 2023",
    completionDate: "February 13, 2023",
    credentialId: "GD-BRAND-992",
    verificationLink: "https://dribbble.com",
    category: "UI/UX & Design",
    skills: ["Graphic Design", "UI/UX"],
    description: "Color theory, luxury editorial typography, vector illustration, visual composition, and brand identity design guidelines.",
    featured: false,
    order: 27,
    createdAt: "2023-02-13T00:00:00Z"
  },
  {
    id: "cert-28",
    title: "Visual Media Arts & Composition Excellence",
    fileName: "certificate2.png",
    fileType: "image",
    fileUrl: "/certificates/certificate2.png",
    organization: "Visual Media Guild",
    courseName: "Visual Media Arts & Composition",
    issueDate: "March 2023",
    completionDate: "March 20, 2023",
    credentialId: "VMA-CERT-02",
    verificationLink: "https://instagram.com/nipunkushwah",
    category: "UI/UX & Design",
    skills: ["Photography", "Graphic Design"],
    description: "Advanced photo manipulation, lighting composition, visual storytelling, and digital image editing workflows.",
    featured: false,
    order: 28,
    createdAt: "2023-03-20T00:00:00Z"
  },
  {
    id: "cert-29",
    title: "Professional Photography & Visual Storytelling",
    fileName: "CERTIFICATE.png",
    fileType: "image",
    fileUrl: "/certificates/CERTIFICATE.png",
    organization: "National Photographic Arts Society",
    courseName: "Professional Photography & Fine Art Composition",
    issueDate: "January 2023",
    completionDate: "January 15, 2023",
    credentialId: "PHOTO-ART-2023",
    verificationLink: "https://unsplash.com",
    category: "UI/UX & Design",
    skills: ["Photography", "Graphic Design"],
    description: "Mastery in camera optics, manual exposure control, golden ratio framing, portraiture, and high-dynamic-range color grading.",
    featured: false,
    order: 29,
    createdAt: "2023-01-15T00:00:00Z"
  },
  {
    id: "cert-30",
    title: "Generative Neural Network Architectures",
    fileName: "Coursera 0GDXWWG535KS (1).pdf",
    fileType: "pdf",
    fileUrl: "/certificates/Coursera%200GDXWWG535KS%20(1).pdf",
    organization: "DeepLearning.AI / Coursera",
    courseName: "Generative Neural Network Architectures",
    issueDate: "February 2024",
    completionDate: "February 05, 2024",
    credentialId: "0GDXWWG535KS-ADV",
    verificationLink: "https://coursera.org/verify/0GDXWWG535KS",
    category: "AI & Machine Learning",
    skills: ["Artificial Intelligence", "Python"],
    description: "Generative Adversarial Networks (GANs), Diffusion Models, Variational Autoencoders (VAEs), and latent space manipulation.",
    featured: false,
    order: 30,
    createdAt: "2024-02-05T00:00:00Z"
  }
];

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    name: "Core Engineering & Languages",
    description: "Systems programming, object-oriented design, and modern scripting languages.",
    skills: [
      { name: "Java", level: "Advanced", experienceYears: "3+ Yrs", category: "Core Engineering", highlight: true },
      { name: "Python", level: "Advanced", experienceYears: "4+ Yrs", category: "Core Engineering", highlight: true },
      { name: "C++", level: "Proficient", experienceYears: "3+ Yrs", category: "Core Engineering", highlight: true },
      { name: "C", level: "Proficient", experienceYears: "2+ Yrs", category: "Core Engineering" },
      { name: "JavaScript", level: "Advanced", experienceYears: "4+ Yrs", category: "Core Engineering", highlight: true }
    ]
  },
  {
    name: "Full-Stack Web Architecture",
    description: "Modern component-driven frontends, reactive backends, and cloud databases.",
    skills: [
      { name: "React", level: "Advanced", experienceYears: "3+ Yrs", category: "Full-Stack Web", highlight: true },
      { name: "Next.js", level: "Advanced", experienceYears: "3+ Yrs", category: "Full-Stack Web", highlight: true },
      { name: "Node.js", level: "Advanced", experienceYears: "3+ Yrs", category: "Full-Stack Web", highlight: true },
      { name: "Express.js", level: "Advanced", experienceYears: "3+ Yrs", category: "Full-Stack Web" },
      { name: "MongoDB", level: "Proficient", experienceYears: "2+ Yrs", category: "Full-Stack Web" },
      { name: "HTML", level: "Mastering", experienceYears: "5+ Yrs", category: "Full-Stack Web" },
      { name: "CSS", level: "Mastering", experienceYears: "5+ Yrs", category: "Full-Stack Web" },
      { name: "Tailwind CSS", level: "Mastering", experienceYears: "3+ Yrs", category: "Full-Stack Web", highlight: true }
    ]
  },
  {
    name: "DevOps, Version Control & Tools",
    description: "Distributed code repositories, CI/CD pipelines, and cloud platform tools.",
    skills: [
      { name: "Git", level: "Mastering", experienceYears: "4+ Yrs", category: "DevOps & Tools" },
      { name: "GitHub", level: "Mastering", experienceYears: "4+ Yrs", category: "DevOps & Tools", highlight: true }
    ]
  },
  {
    name: "Design, Media & Creative Arts",
    description: "Editorial UI design systems, brand identity crafting, and fine art photography.",
    skills: [
      { name: "UI/UX", level: "Advanced", experienceYears: "3+ Yrs", category: "Design & Creative", highlight: true },
      { name: "Graphic Design", level: "Advanced", experienceYears: "4+ Yrs", category: "Design & Creative", highlight: true },
      { name: "Photography", level: "Mastering", experienceYears: "4+ Yrs", category: "Design & Creative", highlight: true }
    ]
  },
  {
    name: "Specialized Intelligence & Defense",
    description: "Neural network architectures, LLM prompt engineering, and defensive cybersecurity.",
    skills: [
      { name: "Artificial Intelligence", level: "Advanced", experienceYears: "2+ Yrs", category: "Specialized", highlight: true },
      { name: "Cyber Security", level: "Proficient", experienceYears: "2+ Yrs", category: "Specialized", highlight: true }
    ]
  }
];
